meta_product_name: "Up in the Air"
meta_title: "Up in the Air - Not endorsed by George Clooney"
meta_description: "Arrange trips with your friends, no matter where in the world they live."
meta_image: "london.jpg" # TODO: change this image as per https://trello.com/c/dxf6pGfE/36-ogimage-has-the-right-dimensions
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
